tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'bash'
brew 'bash-completion'
brew 'direnv'
brew 'docker-compose'
brew 'fd'
brew 'git'
brew 'gh'
brew 'git-lfs'
brew 'htop'
brew 'jq'
brew 'neovim'
brew 'ripgrep'
brew 'tmux'
brew 'tree'
brew 'zoxide'
brew 'node'
brew 'zsh'
brew 'fzf'
brew 'exa'
brew 'starship'
brew 'readline'
brew 'xz'
brew 'reattach-to-user-namespace'
brew 'gpg'
brew 'gnupg2'
brew 'pinentry'
brew 'fnm'
brew 'rust'
brew 'topgrade'
brew 'bat'
brew 'luarocks'
brew 'efm-langserver'
brew 'sd'
brew 'ninja'
brew 'cargo'
brew 'asdf'

cask 'docker'

if (File.file?('Brewfile.local'))
  instance_eval(File.read('Brewfile.local'))
end
