local present, treesitter = pcall(require, 'nvim-treesitter.configs')
if not present then
  return
end

treesitter.setup({
  autopairs = { enable = true },
  autotag = {
    enable = true,
    filetypes = {
      'html',
      'javascript',
      'javascriptreact',
      'typescriptreact',
      'tsx',
      'svelte',
      'vue',
      'heex',
    },
  },
  rainbow = { enable = true, extended_mode = false, max_file_lines = 2000 },
  ensure_installed = {
    'bash',
    'comment',
    'css',
    'dockerfile',
    'dot',
    'eex',
    'elixir',
    'erlang',
    'fennel',
    'gleam',
    'go',
    'graphql',
    'hcl',
    'heex',
    'html',
    'javascript',
    'jsdoc',
    'json',
    'json5',
    'jsonc',
    'lua',
    'prisma',
    'python',
    'regex',
    'rust',
    'scss',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'yaml',
  },
  highlight = { enable = true, use_languagetree = true },
  refactor = { highlight_definitions = { enable = true }, navigation = { enable = true } },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = '<CR>',
      scope_incremental = '<CR>',
      node_incremental = '<TAB>',
      node_decremental = '<S-TAB>',
    },
  },
})
